### ISSUE TITLE
Instructions in ReadMe seem to be incorrect

### ISSUE THREAD

**Issue by nickalleyne** [xpherism/udm-proxy#1]
Hi there,

It seems the instructions in readme are incorrect, particularly around the symlink, and ensuring it is in onboot.d .

Unless I am doing it completely wrong, the symlinking is not linking where it should be for the booting, and even the initial run.

Thanks for looking into this!

**Comment by xpherism** [comment]
You absolutely correct :-) Thank you for pointing it out. I've fixed the readme.
